define([
        //'./BorderContainer',
        './store/FileConverter',
        './store/FileStore',
        './store/JsonConverter'/*,
        './createValueFactory',
        './StoreViewController',
        './TemplateRefArrayResolver',
		'./MultiTemplateRefResolver',
		'./MultiTemplateRefArrayResolver',
		'./TemplateRefResolver',
		'./Renderer',
 		'./UrlTreeModel',
		'./TreeStore',
		'./RequiredAttributes',
		'./SchemaResolver',
		'./DynamicResourceManager'*/
	], function () {
	}
);
